import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { Poppins } from "next/font/google";
import theme from "./ui/theme";
import Header from "./ui/components/Header";
import Sidebar from "./ui/components/Sidebar";
import Footer from "./ui/components/Footer";
import Toolbar from "@mui/material/Toolbar";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={poppins.variable}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Header />
            <Toolbar sx={{ minHeight: { sm: "88px" } }} />
            <Sidebar />
            <main
              style={{
                minHeight: "calc(100vh - 64px - 32px)", // adjust for header + footer height
                paddingTop: "16px",
                marginLeft: "calc(235px + 32px)",
                marginRight: "32px",
              }}
            >
              {props.children}
            </main>
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
